### ISSUE TITLE
The Title of Update Form Says 'Add New Member' despite this is UPDATE Form

### ISSUE THREAD

**Issue by NischalLal** [NischalLalShrestha/class-ultimate-classof2020#2]
In members/detail.html, Same block is used for both updating and creating member.

![issue001](https://user-images.githubusercontent.com/26851181/31655125-a227ae80-b347-11e7-86bb-c804013f0332.png)
@NischalLalShrestha 
`

**Comment by theonlyNischal** [comment]
[This commit fix this issue](https://github.com/NischalLalShrestha/class-ultimate-classof2020/commit/46e70ebf95114541fe2015154a731efea718528a)
